== VimRegexTutor

__A "hands on" regular expression tutorial for users of the Vim editor.__

TIP: If you like VimRegexTutor and want to share the W00t!, I'm grateful for
https://www.gittip.com/bairuidahu/[tips] or
http://of-vim-and-vigor.blogspot.com/[beverages].

[horizontal]
**Project Page** :: https://github.com/dahu/VimRegexTutor
**Maintainer**   :: Barry Arthur <barry.arthur@gmail.com>
**Status**       :: Beta, feedback welcome
**Adapted From** :: http://www.codeproject.com/Articles/9099/The-30-Minute-Regex-Tutorial

Most new users can get through it in less than one hour. The result is that you
can use simple regular expressions using the Vim editor.

=== `:VimRegexTutor`

The `:VimRegextutor` command will open a new tab containing an editable copy of
the tutorial. Have at it!

=== Old School

`regextutor` is a file that contains the tutorial lessons. You can simply
execute `vim regextutor` and then follow the instructions in the lessons.  The
lessons tell you to modify the file, so *DON'T DO THIS ON YOUR ORIGINAL COPY*.

On Unix you can also use the `vimregextutor` program.  It will make a scratch
copy of the tutor first. Currently, this program needs to be manually installed
into a directory in your PATH. Assuming you used pathogen to install
VimRegexTutor, you could do something like:

    cd
    mkdir -p bin
    ln -s $HOME/.vim/bundle/VimRegexTutor/bin/vimregextutor $HOME/bin/vimregextutor

**NOTE:** This is a once-off setup and won't need to be repeated after
upgrading VimRegexTutor.
